# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(573, 339)
        self.Recognition = QtWidgets.QPushButton(Menu)
        self.Recognition.setGeometry(QtCore.QRect(200, 50, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Recognition.setFont(font)
        self.Recognition.setObjectName("Recognition")
        self.Viewlog = QtWidgets.QPushButton(Menu)
        self.Viewlog.setGeometry(QtCore.QRect(200, 110, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Viewlog.setFont(font)
        self.Viewlog.setObjectName("Viewlog")
        self.Newuser = QtWidgets.QPushButton(Menu)
        self.Newuser.setGeometry(QtCore.QRect(200, 170, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Newuser.setFont(font)
        self.Newuser.setObjectName("Newuser")
        self.Logout = QtWidgets.QPushButton(Menu)
        self.Logout.setGeometry(QtCore.QRect(200, 230, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Logout.setFont(font)
        self.Logout.setObjectName("Logout")

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "Menu"))
        self.Recognition.setText(_translate("Menu", "Start Recognition"))
        self.Viewlog.setText(_translate("Menu", "View Log"))
        self.Newuser.setText(_translate("Menu", "New User"))
        self.Logout.setText(_translate("Menu", "Log out"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Menu = QtWidgets.QWidget()
    ui = Ui_Menu()
    ui.setupUi(Menu)
    Menu.show()
    sys.exit(app.exec_())
