# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Rcognition.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Rcognition(object):
    def setupUi(self, Rcognition):
        Rcognition.setObjectName("Rcognition")
        Rcognition.resize(1001, 599)
        self.imagelabel = QtWidgets.QLabel(Rcognition)
        self.imagelabel.setGeometry(QtCore.QRect(20, 10, 960, 540))
        self.imagelabel.setStyleSheet("background-color: rgb(186, 186, 186);")
        self.imagelabel.setText("")
        self.imagelabel.setObjectName("label")
        self.stopbutton = QtWidgets.QPushButton(Rcognition)
        self.stopbutton.setGeometry(QtCore.QRect(450, 560, 121, 23))
        self.stopbutton.setObjectName("stopbutton")

        self.retranslateUi(Rcognition)
        QtCore.QMetaObject.connectSlotsByName(Rcognition)

    def retranslateUi(self, Rcognition):
        _translate = QtCore.QCoreApplication.translate
        Rcognition.setWindowTitle(_translate("Rcognition", "Recognition"))
        self.stopbutton.setText(_translate("Rcognition", "Stop and return menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Rcognition = QtWidgets.QWidget()
    ui = Ui_Rcognition()
    ui.setupUi(Rcognition)
    Rcognition.show()
    sys.exit(app.exec_())
